name: CI/CD - Docker Image Verification

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: python-app
  REGISTRY: ghcr.io  # Change to docker.io if using Docker Hub
  PORT: 5000

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to container registry
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/${{ github.repository }}:$GITHUB_SHA .

    - name: Run container and test health
      run: |
        docker run -d --name test-app -p 5000:5000 $REGISTRY/${{ github.repository }}:$GITHUB_SHA
        echo "Waiting for app to be healthy..."
        sleep 10
        curl --fail http://localhost:5000/api/health || (docker logs test-app && exit 1)
        docker stop test-app

    - name: Push Docker image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        docker tag $REGISTRY/${{ github.repository }}:$GITHUB_SHA $REGISTRY/${{ github.repository }}:latest
        docker push $REGISTRY/${{ github.repository }}:$GITHUB_SHA
        docker push $REGISTRY/${{ github.repository }}:latest

    - name: Cleanup
      run: docker system prune -f
