name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: python-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set lowercase repository name
      run: echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/${REPO_LOWERCASE}:$GITHUB_SHA .

    - name: Run container to test health
      run: |
        docker run -d --name test-app -p 5000:5000 $REGISTRY/${REPO_LOWERCASE}:$GITHUB_SHA
        echo "Waiting for app to become healthy..."
        sleep 10
        curl --fail http://localhost:5000/api/health || (docker logs test-app && exit 1)
        docker stop test-app
        docker rm test-app

    - name: Push Docker image to GHCR
      run: |
        docker tag $REGISTRY/${REPO_LOWERCASE}:$GITHUB_SHA $REGISTRY/${REPO_LOWERCASE}:latest
        docker push $REGISTRY/${REPO_LOWERCASE}:$GITHUB_SHA
        docker push $REGISTRY/${REPO_LOWERCASE}:latest

