name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write    # Required for GHCR push
      id-token: write    # Needed for OIDC if you use it

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase names
        run: |
          USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "IMAGE=${{ env.REGISTRY }}/${USERNAME}/${REPO_NAME}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:${{ github.sha }} .

      - name: Tag Docker image as latest
        run: |
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
